config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects do
    resources :rewards
    member do
      patch :submit
      get :preview
    end
  end

  resources :admins do
    member do
      patch :approve
      patch :reject
      patch :add_comment
    end
  end

  resources :users do
    member do
      get :backed
    end
  end

  resources :uploads, only: [:create, :destroy]

  resources :myprojects, only: [:index]
  resources :stories, only: [:edit, :update]
end

app/views/admins/index.html.erb
<h2 class="my-4">Projects List</h2>

<%= search_form_for @q, url: admins_path do |f| %>
  <%= f.label :id, "ID" %>
  <%= f.search_field :id_eq %>

  <%= f.label :admin_comment, "comment" %>
  <%= f.search_field  :admin_comment_cont %>


  <%= f.label :goal %>
  <%= f.number_field :goal_gteq %>Greater than〜
  <%= f.number_field :goal_lt %>Less than

  <%= f.submit "Search" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Project ID</th>
      <th scope="col">Funding Goal</th>
      <th scope="col">Campaign Duration</th>
      <th scope="col">User Name</th>
      <th scope="col"><%= sort_link(@q, :created_at, "Date") %></th>
      <th scope="col">Comment</th>
      <th scope="col">Check</th>
    </tr>
  </thead>
  <tbody>
   <% @reviewing_projects.each do |reviewing_project| %>

    <% if reviewing_project.errors.any? %>
      <% reviewing_project.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    <% end %>

    <tr>
      <th scope="row"><%= link_to reviewing_project.id, admin_path(reviewing_project) %></th>
      <td><%= reviewing_project.goal %></td>
      <td><%= reviewing_project.duration %></td>
      <td><%= reviewing_project.user.username %></td>
      <td><%= reviewing_project.created_at %></td>
      <td>
        <%= form_with model: reviewing_project, url: add_comment_admin_path(reviewing_project) do |f| %>
          <%= f.text_area :admin_comment, :class => "form-control" %>
          <%= f.submit "Save"%>
        <% end %>
      </td>
      <td class="btn btn-success mt-1"><%= link_to "Approve", approve_admin_path(reviewing_project), method: :patch, class: "text-white" %></td>
      <td class="btn btn-danger ml-2 px-4 mt-1"><%= link_to "Reject", reject_admin_path(reviewing_project), method: :patch, class: "text-white" %></td>
    </tr>
   <% end %>
   <%= paginate @reviewing_projects %>
  </tbody>
</table>

app/views/admins/show.html.erb
<div class="check-project">
  <%= render 'layouts/showproject' %>
<div>

<script>
  let elems = document.getElementById('foo');
  let imgElems = elems.getElementsByTagName('img');
  for(let i = 0; i < imgElems.length; i++){
      imgElems.item(i).classList.add('img-fluid');
  }
  let videoElems = elems.getElementsByTagName('iframe');
  for(let i = 0; i < videoElems.length; i++){
      videoElems.item(i).parentElement.classList.add('embed-responsive', 'embed-responsive-16by9');
  }
</script>