config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects do
    resources :rewards
    member do
      patch :submit
      get :preview
    end
  end

  resources :admins do
    member do
      patch :approve
      patch :reject
      patch :add_comment
    end
  end

  resources :users do
    member do
      get :backed
    end
  end

  resources :uploads, only: [:create, :destroy]

  resources :myprojects, only: [:index]
  resources :stories, only: [:edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy, foreign_key: 'user_id'

  validates :username, presence: true, length: { maximum: 30 }

  WEB_REGEXP = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix
  validates :website,
    format: { with: WEB_REGEXP, message: 'You provided invalid URL' },
    allow_blank: true

  #validates :instagram,
    #format: { with: /(https?)?:?(www)?instagram\.com/[a-z].{3}\z/ig,
      #message: 'url you provided is invalid.' },
    #allow_blank: true

  #validates :twitter,
    #format: { with:  https?:\/\/(.*\.)?twitter\.com\/[A-z0-9_]+\/?,
      #message: 'url you provided is invalid.' }
    #allow_blank: true

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_user, only: [:edit, :update]

    def show
        @user = User.find(params[:id])
        @projects = @user.projects.page(params[:page]).per(8)
    end

    def backed
        @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
          flash[:notice] = "User profile successfully updated."
          redirect_to edit_user_path(@user)
      else
          render 'edit'
          #redirect_to edit_user_path(@user)
      end
    end


    private

      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user === @user
      end

      def user_params
        params.require(:user).permit(:username, :avatar, :location, :website, :twitter, :instagram, :bio)
      end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userinfo.html.erb
<div class="container-fluid user-show">
  <div class="user-show-header bg-light">
    <div class="row user-avatar pt-5 pb-3 justify-content-center">
        <% if @user.avatar? %>
            <%= image_tag @user.avatar.url, alt: 'user avatar', :class => "img-fluid rounded-circle" %>
        <% else %>
            <img class="img-fluid rounded-circle" src="/assets/noavatar.png" alt="user avatar" width="150" height="150" >
        <% end %>
    </div>
    <div class="user-info text-center">
      <h2 class="font-weight-bold mb-3"><%= @user.username %></h2>
      <% if @user.bio? %>
        <h5 class="mb-3"><%= @user.bio %></h5>
      <% end %>

      <% if @user.website? %>
        <a class="mb-5 text-secondary" href="<%= @user.website %>"><%= icon('fas', 'globe', :class => "mx-1", :style => 'font-size: 20px;') %></a>
      <% end %>
      <% if @user.twitter? %>
        <a class="mb-5 text-secondary" href="https://www.twitter.com/<%= @user.twitter %>/"><%= icon('fab', 'twitter-square', :class => "mx-1", :style => 'font-size: 20px;') %></a>
      <% end %>
      <% if @user.instagram? %>
        <a class="mb-5 text-secondary" href="https://www.instagram.com/<%= @user.instagram %>/"><%= icon('fab', 'instagram', :class => "mx-1", :style => 'font-size: 20px;') %></a>
      <% end %>

      <% if @user.location? %>
        <p class="my-2 text-secondary"><%= @user.location %></p>
      <% end %>

      <p class="text-secondary pb-4 pt-1">Joined <%= @user.created_at.strftime('%b %Y') %></p>
    </div>

  </div>

  <div class="user-show-content row justify-content-center border-bottom">
    <ul class="nav nav-tab-user">
        <li class="nav-item">
            <%= link_to "Created Projects #{@user.projects.approved_projects.count}" , user_path(@user), :class => "nav-link user-nav-content #{ params[:action] == 'show' ? 'active' : '' }" %>
        </li>
        <li class="nav-item">
            <%= link_to "Backed Projects 0" , backed_user_path(@user), :class => "nav-link user-nav-content #{ params[:action] == 'backed' ? 'active' : '' }"%>
        </li>
    </ul>
  </div>
</div>

app/views/users/backed.html.erb
<%= render 'users/userinfo'%>

app/views/users/edit.html.erb
<div class="bg-light py-5">

    <div class="container">

      <div class="row">
        <div class="col-md-4 order-md-2 mb-5">
          <h4 class="d-flex justify-content-between align-items-center">
            <h3 class="text-muted">Setting</h3>
          </h4>
          <ul class="list-group my-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed py-4">
              <div>
                <h6 class="my-0">Profile</h6>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed py-4">
              <div>
                <h6 class="my-0">Payment</h6>
              </div>
            </li>
          </ul>
        </div>

        <div class="col-md-8 order-md-1">
          <h3 class="mb-4">Edit Profile</h3>
          <hr class="mb-4">
          <div class="needs-validation" novalidate>
          <%= form_with model: @user, url: user_path, method: :patch, local: true do |f| %>

            <div class="text-center mx-auto my-4" style="width: 600px;">
                <% if @user.errors.any? %>
                    <ul class="list-group">
                    <% @user.errors.full_messages.each do |message| %>
                        <li class="list-group-item list-group-item-danger "><%= icon('fas', 'exclamation-triangle', :class => "mr-2") %><%= message %> </li>
                    <% end %>
                    </ul>
                <% end %>
            </div>

            <div class="row">
              <div class="col-md-6 mb-3">
                <%= f.label :username %>
                <%= f.text_field :username, :class => "form-control", :placeholder => "Please enter your name." %>
                <div class="invalid-feedback">
                  Valid name is required.
                </div>
              </div>
            </div>

            <div class="my-4">
              <%= f.label :avatar %>
              <p>Recommnd size: Greater than 200px*200px</p>
              <div class="input-group">
                <%= f.file_field :avatar, :class => "form-control-file", id: "post_img" %>
                <%= f.hidden_field :avatar_cache %>
                <div class="mt-5">
                  <%= image_tag @user.avatar.thumb.url, class: "avatar_present_img" if @user.avatar? %>
                </div>
                <img id="avatar_img_prev" src="#" class='d-none' width="150" height="150"  />
              </div>
            </div>

           <div class="my-4">
              <%= f.label :bio %>
              <%= f.text_area :bio, :class => "form-control", :placeholder => "Hello my name is Taro. " %>
            </div>

            <div class="my-4">
              <%= f.label :location %>
              <%= f.text_field :location, :class => "form-control", :placeholder => "Tokyo, Japan" %>
            </div>

            <div class="my-4">
              <%= icon('fas', 'globe', :class => "mr-2") %><%= f.label :webiste %>
              <%= f.text_field :website, :class => "form-control", :placeholder => "http://blog.com" %>
            </div>

            <div class="my-4">
              <%= icon('fab', 'twitter-square', :class => "mr-2") %><%= f.label :twitter %> (Username)
              <%= f.text_field :twitter, :class => "form-control", :placeholder => "Twitter" %>
            </div>

            <div class="my-4">
              <%= icon('fab', 'instagram', :class => "mr-2") %><%= f.label :instagram %> (Username)
              <%= f.text_field :instagram, :class => "form-control", :placeholder => "instagram" %>
            </div>

            <hr class="my-4">
            <%= f.submit "Save", disable_with: 'Submiting...', :class => "btn btn-primary btn-lg btn-block" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'users/userinfo'%>

   <div class="container mb-5">
      <div class="row d-flex">
         <% @projects.approved_projects.each do |project| %>
         <div class="col-lg-3 col-md-4 col-sm-6 col-12 mt-5">
            <!-- Card -->

            <div class="card border-0 shadow">
               <!-- Card image -->
               <div class="view">
                 <%= link_to project_path(project), :class => "project-img" do %>
                  <% if project.image? %>
                    <%= image_tag project.image.url, alt: 'project image', :class => "img-fluid card-img-top rounded-top" %>
                  <% else %>
                    <img class="img-fluid card-img-top rounded-top" src="/assets/noimage.png" alt="project image">
                  <% end %>
                 <% end %>
                  <a href="#!">
                     <div class="mask rgba-white-slight"></div>
                  </a>
               </div>
               <!-- Card content -->
               <div class="card-body border rounded-bottom">
                  <%= link_to project.category, projects_path(category: project.category) , :class => "card-text small mr-1 d-inline-block" %>
                  <!-- Title -->
                  <%= link_to project_path(project), :class => "card-title project-title" do %>
                    <%= project.title %>
                  <% end %>
                  <!-- Description -->
                  <hr>
                  <ul class="list-unstyled d-flex justify-content-between mb-3 text-center small">
                     <li class="pledged">
                        <p class="mb-1 font-weight-bold text-dark">Pledged</p>
                        <span class="amount"><%= project.goal %></span>
                     </li>
                     <li class="funded">
                        <p class="mb-1 font-weight-bold text-dark">Funded</p>
                        <span class="amount">$0</span>
                     </li>
                     <li class="days">
                        <p class="mb-1 font-weight-bold text-dark">Days Left</p>
                        <span class="amount"><%= project.date_diff %></span>
                     </li>
                  </ul>
                  <div class="progress mb-2">
                     <!-- ${} が使える -->
                     <div class="progress-bar bg-success" role="progressbar" aria-valuenow="55" aria-valuemin="91" aria-valuemax="100" style="width:62%">62%</div>
                  </div>
                  <!-- end: progress bard -->
               </div>
            </div>
            <!-- Card -->
         </div>
         <% end %>
         <!-- end col -->
         <div class="mx-auto mt-5"><%= paginate @projects.approved_projects, window: 2 %></div>
      </div>
   </div>