config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects do
    resources :rewards
    member do
      patch :submit
      get :preview
    end
  end

  resources :admins do
    member do
      patch :approve
      patch :reject
      patch :add_comment
    end
  end

  resources :users do
    member do
      get :backed
    end
  end

  resources :uploads, only: [:create, :destroy]

  resources :myprojects, only: [:index]
  resources :stories, only: [:edit, :update]
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    validates :user_id, presence: true
    has_many :rewards, dependent: :destroy

    validate :duration_cannot_be_in_the_past
    validates :goal,
      numericality: {only_integer: true, greater_than: 0}

    enum category: { Arts: 0, Comics_Illustrator: 1, Design_Tech: 2, Film: 3, Food_Craft: 4, Games: 5, Music: 6, Pablishing: 7}
    enum location: { Taiwan: 0, Japan: 1, Others: 2}

    def date_diff
      dif = self.duration - Date.today
      return dif.to_i
    end

    def self.approved_projects
      self.where(reviewing: true).where(reviewed: true)
    end

    def self.reviewing_projects
      self.where(reviewing: true).where(reviewed: false)
    end

    def self.private_projects
      self.where(reviewing: false).where(reviewed: false)
    end

    private
      def duration_cannot_be_in_the_past
          errors.add(:duration, "can't be in the past") if duration < Date.today
      end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :correct_user, only: [:edit, :update, :submit, :preview]
    before_action :set_project, only: [:edit, :update, :submit, :preview]
    before_action :reviewed_projects, only: [:show]

    def index
        if params[:category]
            @projects = Project.where(reviewing: true).where(reviewed: true).where(category: params[:category]).page(params[:page]).per(12)
        else
            @projects = Project.where(reviewing: true).where(reviewed: true).page(params[:page]).per(12)
        end
    end

    def show
        @project = Project.find(params[:id])
    end

    def new
        @project = current_user.projects.build
    end

    def create
        @project = current_user.projects.create!(
            title: nil, subtitle: nil, category: nil, image: nil, goal: 1, duration: Date.today + 1, story: nil, location: nil
        )
        redirect_to edit_project_path(@project)
    end

    def edit
    end

    def update
        if @project.update_attributes(project_params)
            flash[:notice] = "Basics was successfully updated."
            redirect_to project_rewards_path(@project)
        else
            render 'edit'
            #redirect_to edit_project_path(@project)
        end
    end

    def submit
        if @project.update_attributes(reviewing: true)
            flash[:notice] = "Your project was successfully submitted. Your project will be reviewed by us. Please wait a few days until notification will come."
            redirect_to root_path
        else
            puts @project.errors.full_messages
            redirect_to edit_project_path(@project)
        end
    end

    def preview
    end

    private
      def project_params
        params.require(:project).permit(:title, :subtitle, :category, :image, :goal, :duration, :story, :location)
      end

      def correct_user
        @project = current_user.projects.find_by(id: params[:id])
        redirect_to root_path if @project.nil?
      end

      def set_project
        @project = current_user.projects.find(params[:id])
      end

      def reviewed_projects
        @project = Project.find(params[:id])
        redirect_to edit_project_path(@project) unless @project.reviewing? && @project.reviewed?
      end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<%= render 'layouts/projectnav' %>

<div class="basic-form mt-5 container">

  <div class="text-center my-5">
    <h4 class="font-weight-bold">Basics</h4>
    <h5>Make it simple for individuals to learn about your project.</h5>
  </div>

  <%= form_with model: @project, local: true do |f| %>

  <div class="text-center mx-auto" style="width: 300px;">
    <% if @project.errors.any? %>
      <ul class="list-group">
      <% @project.errors.full_messages.each do |message| %>
        <li class="list-group-item list-group-item-danger "><%= icon('fas', 'exclamation-triangle', :class => "mr-2") %><%= message %> </li>
      <% end %>
      </ul>
    <% end %>
  </div>


  <div class="form-group row my-5">
    <div class="col-sm-2"></div>
    <div class="col-sm-2 col-form-label mr-5 project-label">
      <label class=" font-weight-bold"><%= f.label :title %></label>
      <p>Write a catchy and simple title.</p>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :title, :class => "form-control", :placeholder => "Please enter your project title.", onkeyup: 'ShowLength(value)', :maxlength => '30', disabled: @project.reviewing? && @project.reviewed? %>
      <div id="wordcnt" class="text-right">
        <% if @project.title.present? %>
          <%= @project.title.length %>/30
        <% else %>
          0/30
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-group row mt-5">
    <div class="col-sm-2"></div>
    <div class="col-sm-2 col-form-label mr-5 project-label">
      <label class="font-weight-bold"><%= f.label :subtitle %></label>
      <p>Write a project summary in about two lines.</p>
    </div>
    <div class="col-sm-6">
      <%= f.text_area :subtitle, :class => "form-control", :placeholder => "Please enter your project's subtitle."%>
    </div>
  </div>

  <div class="form-group row mt-5">
    <div class="col-sm-2"></div>
    <div class="col-sm-2 col-form-label mr-5 project-label">
      <label class="font-weight-bold"><%= f.label :category %></label>
      <p>Please choose the category.</p>
    </div>
    <div class="col-sm-2">
      <%= f.select :category, Project.categories.keys.map {|k| [k, k]}, {},:class => "custom-select" %>
    </div>
  </div>

  <div class="form-group row mt-5">
    <div class="col-sm-2"></div>
    <div class="col-sm-2 col-form-label mr-5 project-label">
      <label class="font-weight-bold"><%= f.label :image %></label>
      <p>Add an image that attract viewer's attention.</p>
      <p>preferred image size: 1024x576 pixels (16 : 9 ratio).</p>
    </div>
    <div class="col-sm-6">
      <%= f.file_field :image, :class => "form-control-file", id: "post_img" %>
      <%= f.hidden_field :image_cache %>
      <div class="mt-5">
        <%= image_tag @project.image.thumb.url, class: "avatar_present_img" if @project.image? %>
      </div>
      <img id="avatar_img_prev" src="#" class='d-none' width="320" height="180"  />
    </div>
  </div>

  <div class="form-group row mt-5">
    <div class="col-sm-2"></div>
    <div class="col-sm-2 col-form-label mr-5 project-label">
      <label class="font-weight-bold"><%= f.label :goal %></label>
      <p>Set your project goal. </p>
      <p>Note that funding is All-or-Nothing.</p>
      <p>So please make sure not to set an unachievable goal.</p>
    </div>
    <div class="col-sm-2">
      <%= f.number_field :goal, :class => "form-control", :placeholder => "300", disabled: @project.reviewing? && @project.reviewed? %>
    </div>
  </div>

  <div class="form-group row mt-5">
    <div class="col-sm-2"></div>
    <div class="col-sm-2 col-form-label mr-5 project-label">
      <label class="font-weight-bold"><%= f.label :duration %></label>
      <p>Set a time limit.</p>
      <p>Projects with a duration of 65 days or less have a higher success rate.</p>
    </div>
    <div class="col-sm-3">
      <%= f.date_field :duration, :class => "custom-select", disabled: @project.reviewing? && @project.reviewed? %>
    </div>
  </div>

  <div class="form-group row mt-5 mb-5">
    <div class="col-sm-2"></div>
    <div class="col-sm-2 col-form-label mr-5 project-label">
      <label class="font-weight-bold"><%= f.label :location %></label>
      <p>Choose your location of project.</p>
    </div>
    <div class="col-sm-2">
      <%= f.select :location, Project.locations.keys.map {|k| [k, k]}, {}, :class => "custom-select" %>
    </div>
  </div>

  <div class="fixed-bottom text-center border-top bg-light py-2">
    <%= link_to "Preview", preview_project_path(@project), :class => "btn btn-success btn-lg px-4 mr-5" %>
    <%= f.submit "Save", disable_with: 'Submiting...', :class => "btn btn-info btn-lg px-5 " %>
  </div>

  <% end %>
</div>

<script>
  BorderDevice();
  window.onresize = function() {
    BorderDevice();
  }
</script>

app/views/projects/index.html.erb
   <div class="new-project text-center py-5 border-bottom bg-light">
     <%= link_to "Start a project", new_project_path, :class => "btn btn-info btn-lg" %>
   </div>

   <% if params[:category] %>
      <h4 class="mt-5 font-weight-bold container"><%= icon('fas', 'tag', :class => "mr-2") %><%= params[:category] %></h4>
   <% elsif  params[:q] %>
      <% if params[:q][:category] %>
         <h4 class="mt-5 font-weight-bold container"><%= icon('fas', 'tag', :class => "mr-2") %><%= params[:q][:category] %></h4>
      <% else %>
         <h4 class="mt-5 font-weight-bold container">
         <%= icon('fas', 'tag', :class => "mr-2") %>
         <%= @search_projects.count %> results for "<%= params[:q][:story_or_title_cont] %>"
         </h4>
      <% end %>
   <% else %>
      <div class="text-center border-bottom py-3">
         <% Project.categories.each do |category| %>
           <%= link_to category[0], projects_path(category: category[0]), :class => "mx-3 text-secondary" %>
         <% end %>
      </div>
   <% end %>

   <div class="container mb-5">
     <% if params[:q] || params[:category] %>
      <%= search_form_for @search, url: projects_path do |f| %>
      <div class="bg-light py-3 form-inline justify-content-center mt-4">
        <div class="m-2">
          Category:    <%= f.select :category, Project.categories.keys.map {|k| [k, k]}, { selected: params[:q] ? params[:q][:category] : params[:category] }, onchange: 'this.form.submit()', :class => "custom-select" %>
        </div>
        <div class="m-2">
          <%= sort_link(@search, :created_at, default_order: :desc) do %>
            <div class="btn btn-secondary">Created Date</div>
          <% end %>
        </div>
      </div>
      <% end %>
     <% end %>

      <div class="row d-flex">
         <% @search_projects.each do |project| %>
         <div class="col-lg-3 col-md-4 col-sm-6 col-12 mt-5">
            <!-- Card -->

            <div class="card border-0 shadow">
               <!-- Card image -->
               <div class="view">
                 <%= link_to project_path(project), :class => "project-img" do %>
                  <% if project.image? %>
                    <%= image_tag project.image.url, alt: 'project image', :class => "img-fluid card-img-top rounded-top" %>
                  <% else %>
                    <img class="img-fluid card-img-top rounded-top" src="/assets/noimage.png" alt="project image">
                  <% end %>
                 <% end %>
                  <a href="#!">
                     <div class="mask rgba-white-slight"></div>
                  </a>
               </div>
               <!-- Card content -->
               <div class="card-body border rounded-bottom">
                  <%= link_to project.category, projects_path(category: project.category) , :class => "card-text small mb-2 d-block" %>
                  <!-- Title -->
                  <%= link_to project_path(project), :class => "card-title project-title" do %><%= project.title %><% end %>
                  <!-- Description -->
                  <hr>
                  <ul class="list-unstyled d-flex justify-content-between mb-3 text-center small">
                     <li class="pledged">
                        <p class="mb-1 font-weight-bold text-dark">Pledged</p>
                        <span class="amount"><%= project.goal %></span>
                     </li>
                     <li class="funded">
                        <p class="mb-1 font-weight-bold text-dark">Funded</p>
                        <span class="amount">$28,000</span>
                     </li>
                     <li class="days">
                        <p class="mb-1 font-weight-bold text-dark">Days Left</p>
                        <span class="amount"><%= project.date_diff %></span>
                     </li>
                  </ul>
                  <div class="progress mb-2">
                     <!-- ${} が使える -->
                     <div class="progress-bar bg-success" role="progressbar" aria-valuenow="55" aria-valuemin="91" aria-valuemax="100" style="width:62%">62%</div>
                  </div>
                  <!-- end: progress bard -->
               </div>
            </div>
            <!-- Card -->
         </div>
         <% end %>
         <!-- end col -->
      </div>
      <div class="d-flex justify-content-center mt-5"><%= paginate @search_projects, window: 2 %></div>
   </div>

app/views/projects/new.html.erb
<!--<h1>Let's get started!</h1>
<%= form_with model: @project, local: true do |f| %>
  <%= f.submit "Start a project" %>
<% end %>
-->

<div class="start-project jumbotron">
  <div class="start-project-inner container-fluid">
    <h1 class="text-white font-weight-bold text-center my-3 express-text">Express your creativity to others.</h1>
    <h3 class="text-white text-center my-5 pt-4">You can create a project for free right now !</h3>
    <div class="d-flex justify-content-center my-5 pt-5">
      <%= form_with model: @project, local: true do |f| %>
        <%= f.submit "Start a project", :class => "btn btn-lg btn-gradient-radius px-4 py-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/preview.html.erb
<div class="preview">
    <%= render 'layouts/showproject' %>

    <div class="fixed-bottom text-center border-top bg-light py-2">
      <div class="btn"><%= link_to 'Back to edit page', edit_project_path(@project), class: "btn btn-success " %></div>
    </div>
</div>

app/views/projects/show.html.erb
<div class="show-project">
  <%= render 'layouts/showproject' %>
</div>

app/views/projects/submit.js.erb
$("#request").html("Submitted");