config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects do
    resources :rewards
    member do
      patch :submit
      get :preview
    end
  end

  resources :admins do
    member do
      patch :approve
      patch :reject
      patch :add_comment
    end
  end

  resources :users do
    member do
      get :backed
    end
  end

  resources :uploads, only: [:create, :destroy]

  resources :myprojects, only: [:index]
  resources :stories, only: [:edit, :update]
end

app/views/layouts/_alert.html.erb

<% if notice %>
　 <div class="alert alert-info"><%= notice %>
     <button type="button" class="close" data-dismiss="alert">&times;</button>
   </div>
<% elsif alert %>
   <div class="alert alert-danger"><%= alert %>
     <button type="button" class="close" data-dismiss="alert">&times;</button>
   </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="my-3">
  <div class="text-center border-top">
    <div class="copyright text-center mt-3">
      SampleApp@2019
    <div>

    <div class="select-lang-currency my-3 row justify-content-center">
      <div class="dropdown mb-1 mx-2">

        <button class="btn btn-light dropdown-toggle lang-currency-button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Languages
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to('English', "#", :class => 'dropdown-item') %>
          <%= link_to('日本語', "#", :class => 'dropdown-item') %>
          <%= link_to('中文', "#", :class => 'dropdown-item') %>
        </div>
      </div>

      <div class="dropdown mb-1 mx-2">
        <button class="btn btn-light dropdown-toggle lang-currency-button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Currency
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to('$ US Dollar (USD)', "#", :class => 'dropdown-item') %>
          <%= link_to('¥ Japanese Yen (JYP)', "#", :class => 'dropdown-item') %>
          <%= link_to('NT$ Taiwan Dollar (TWD)', "#", :class => 'dropdown-item') %>
        </div>
      </div>

    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="border-bottom ">
  <div class="container my-2">
    <div class="row align-items-center app-header">

      <div class="searchbox col-md-4">
          <div class="form-group d-inline-flex">
            <%= icon('fas', 'search', class: 'search-icon mr-1') %>
            <%= search_form_for @search, url: projects_path do |f| %>
              <%= f.text_field :story_or_title_cont ,placeholder: 'Search for projects', :class => "form-control form-control-underlined form-search" %>
              <%= f.submit "Search" , class: 'search-btn', style: 'display: none;'%>
            <% end %>
          </div>
      </div>

      <div class="appname col-md-4 my-3">
        <h3 class="text-center font-weight-bold"><%= link_to "APP NAME", root_path %></h3>
      </div>

      <div class="user-page col-md-4 clearfix">
        <% if user_signed_in? %>
          <div class="dropdown">
            <button class="btn btn-secondary btn-circle float-right dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <!--<i class="fas fa-user"></i> -->
              <% if current_user.avatar? %>
                <%= image_tag current_user.avatar.thumb.url, alt: 'user avatar', :class => "img-fluid rounded-circle mb-1" %>
              <% else %>
                <img class="img-fluid rounded-circle mb-1" src="/assets/noavatar.png" alt="user avatar"  >
              <% end %>
            </button>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <div class="dropdown-item" href="#">
                <%= link_to myprojects_path do %>
                  <%= icon('fas', 'pencil-alt', :class => "mr-2") %>My projects
                <% end %>
              </div>
              <a class="dropdown-item" href="#"><%= icon('fas', 'donate', :class => "mr-2") %>Backed projects</a>
              <div class="dropdown-item">
                <%= link_to user_path(current_user) do %>
                  <%= icon('fas', 'user', :class => "mr-2") %>Profile
                <% end %>
              </div>
              <div class="dropdown-item">
                <%= link_to edit_user_path(current_user) do %>
                  <%= icon('fas', 'cog', :class => "mr-2") %>Setting
                <% end %>
              </div>
              <div class="dropdown-item">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <%= icon('fas', 'sign-out-alt', :class => "mr-2") %>Log out
                <% end %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="float-right">
            <div><%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Log in", new_user_session_path %></div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</header>

app/views/layouts/_projectnav.html.erb

<% unless @project.reviewing? %>
  <div id = "request" class=" my-4 container">
      <div class="text-center">
        <%= form_with model: @project, url: submit_project_path(@project) do |f| %>
          <%= f.button :type => "submit", data: { confirm: 'Are you sure?', disable_with: 'Submitting...'}, :class => "btn-custom green rounded" do %>
            <%= icon('fas', 'paper-plane', :class => "mr-2") %>Submit your project.
          <% end %>
        <% end %>
      </div>
  </div>
<% end %>


<div class="select-mode">
  <ul class="nav justify-content-center nav-pills border-bottom border-top py-4">
    <li class="nav-item mx-5">
      <%= link_to "Basics", edit_project_path(@project), :class => "nav-link #{ params[:controller] == 'projects' ? 'active' : '' }" %>
    </li>
    <li class="nav-item mx-5">
      <%= link_to "Rewards", project_rewards_path(@project), :class => "nav-link #{ params[:controller] == 'rewards' ? 'active' : '' }" %>
    </li>
    <li class="nav-item mx-5">
      <%= link_to "Story", edit_story_path(@project), :class => "nav-link #{ params[:controller] == 'stories' ? 'active' : '' }" %>
    </li>
    <li class="nav-item mx-5">
      <a class="nav-link disabled" href="#">Payment</a>
    </li>
  </ul>
<div>

app/views/layouts/_showproject.html.erb
    <div class="bg-light border-top border-bottom">
        <div class="top-heading pb-3 mb-4 container">
            <h1 class="text-center pb-2 mt-5 font-weight-bold"><%= @project.title %></h1>
            <h4 class="text-center text-secondary pb-2"><%= @project.subtitle %></h4>
            <div class="row mt-5">
                <div class="col-lg-8 col-12 mb-2">
                    <% if @project.image? %>
                      <%= image_tag @project.image.url, alt: 'project image', :class => "img-fluid" %>
                    <% else %>
                      <img class="img-fluid" src="/assets/noimage.png" alt="project image">
                    <% end %>

                    <div class="mt-2">
                        <div class="d-inline-block pr-2"><%= icon('fas', 'user', :class => "mr-2") %><%= link_to @project.user.username, user_path(@project.user) %></div>
                        <div class="d-inline-block p-2"><%= icon('fas', 'map-marker-alt', class: 'mr-2') %><%= @project.location %></div>
                        <div class="d-inline-block p-2"><%= icon('fas', 'location-arrow', class: 'mr-2') %><%= link_to @project.category, projects_path(category: @project.category) %></div>
                    </div>
                </div>

                <div class="col-lg-4 col-12">
                  <div class="pl-4">
                    <div class="price-display">
                        <h3 class="pt-4">US$ 0</h3>
                        <p>pledged of US$ <%= @project.goal %> goal</p>
                    </div>

                    <div class="backers mt-3">
                        <h3>0</h3> backers
                    </div>

                    <div class="mt-3">
                        <h3><%= @project.date_diff %></h3> days to go
                    </div>
                  </div>
                    <div class="back-button mt-5">
                        <a href="#" class="btn btn-primary btn-lg btn-block">Back this project</a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="description container mt-5">
        <div class="row">
            <div class="story pl-3 col-md-8 col-xs-12 mb-4">
              <h3 class="mb-5">About</h3>
              <div class="summer" id="foo">
                <% unless @project.story.nil? %>
                  <%= @project.story.html_safe %>
                <% end %>
              </div>
            </div>

            <div class="reward col-md-4 col-xs-12">
              <div class="card text-center my-5 user-card">
                <div class="user-card-img">
                  <%= link_to user_path(@project.user) do %>
                    <% if @project.user.avatar? %>
                      <%= image_tag @project.user.avatar.thumb.url, alt: 'user avatar', :class => "img-fluid rounded-circle" %>
                    <% else %>
                      <img class="img-fluid rounded-circle" src="/assets/noavatar.png" alt="user image" width="80" height="80">
                    <% end %>
                  <% end %>
                </div>
                <div class="card-body pt-5">
                  <h5 class="card-title pt-3"><%= @project.user.username %></h5>
                  <p class="card-text"><%= @project.user.bio %></p>
                  <%= link_to "Go his profile",user_path(@project.user), :class => "btn btn-primary" %>
                </div>
              </div>

              <h3 class="mb-5">Rewards</h3>
              <% @project.rewards.each do |reward| %>
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">Pledge $<%= reward.pledge %> or more</h5>
                        <div class="card-text">
                          <h6><%= reward.title %></h6>
                          <p class="text-secondary"><%= simple_format(h(reward.description)) %></p>
                          <% if reward.limit != 0 %>
                          <div class="limit">
                            <p class="text-secondary mb-0">LIMITED:</p>
                            <p><%= reward.limit %></p>
                          </div>
                          <% end %>
                          <div class="delivery-time">
                            <p class="text-secondary mb-0">ESTIMATED DERIVERY:</p>
                            <p><%= reward.deliverytime %></p>
                          </div>
                          <div class="ship-time">
                            <p class="text-secondary mb-0">SHIPS TO:</p>
                            <p><%= reward.ships %></p>
                          </div>
                        </div>
                        <a href="#" class="btn btn-primary">Select this reward</a>
                    </div>
                </div>
              <% end %>
            </div>
        </div>
    </div>


<script>
  var elems = document.getElementById('foo');
  var imgElems = elems.getElementsByTagName('img');
  for(let i = 0; i < imgElems.length; i++){
      imgElems.item(i).classList.add('img-fluid');
  }
  var videoElems = elems.getElementsByTagName('iframe');
  for(let i = 0; i < videoElems.length; i++){
      videoElems.item(i).parentElement.classList.add('embed-responsive', 'embed-responsive-16by9');
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrowdFunding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <div class="inner">
      <%= render 'layouts/header' %>

      <%= render 'layouts/alert' %>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>